services:
  db:
    image: postgres:17
    container_name: ticketing-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticketing
    ports:
      - "5436:5432"
    volumes:
      - ticketing-pg-data:/var/lib/postgresql/data

volumes:
  ticketing-pg-data:
